weapons:
  test:
    entity: "PLAYER"
    lore:
      suffix: "&e升级进度: "
      symbol: "/"
      max: 100
      #需要手动添加此Lore 格式为
      #%suffix%0%symbol%%max%
      #示例: &e升级进度: 0/100
    #支持类型
    type: "NETHERITE_SWORD"
    #名称识别
    displayname: "&7测试剑I"
    upgrade:
      lore: "&e升级进度: 0/200"
      displayname: "&7测试剑II"
  test2:
    entity: "ZOMBIE"
      lore:
        suffix: "&e升级进度: "
        symbol: "/"
        max: 200
        #需要手动添加此Lore 格式为
        #%suffix%0%symbol%%max%
        #示例: &e升级进度: 0/100
      #支持类型
      type:
        - "NETHERITE_SWORD"
      #名称识别
      displayname: "&7测试剑II"
      upgrade:
        lore: "&e升级进度: 0/300"
        displayname: "&7测试剑III"


